### ISSUE TITLE
Add a logo instead of text

### ISSUE THREAD

**Issue by 18praneeth** [Parthiv-2020/udayagiri-scl-maxo#22]

**Comment by yashss1** [comment]
Hello @18praneeth, I would like to work on this project! Can i know where to add the Logo like in which file?

**Comment by 18praneeth** [comment]
Hi @yashss1 It's nice to know that you want to contribute, but I am extremely sorry as we are not allowed to give permission to those who are not part of the group, this is a group project 😀 .

**Comment by 18praneeth** [comment]
Issue resolved in #25
